// Generated by gencpp from file uuv_control_msgs/GoToRequest.msg
// DO NOT EDIT!


#ifndef UUV_CONTROL_MSGS_MESSAGE_GOTOREQUEST_H
#define UUV_CONTROL_MSGS_MESSAGE_GOTOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uuv_control_msgs/Waypoint.h>

namespace uuv_control_msgs
{
template <class ContainerAllocator>
struct GoToRequest_
{
  typedef GoToRequest_<ContainerAllocator> Type;

  GoToRequest_()
    : waypoint()
    , max_forward_speed(0.0)
    , interpolator()  {
    }
  GoToRequest_(const ContainerAllocator& _alloc)
    : waypoint(_alloc)
    , max_forward_speed(0.0)
    , interpolator(_alloc)  {
  (void)_alloc;
    }



   typedef  ::uuv_control_msgs::Waypoint_<ContainerAllocator>  _waypoint_type;
  _waypoint_type waypoint;

   typedef double _max_forward_speed_type;
  _max_forward_speed_type max_forward_speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _interpolator_type;
  _interpolator_type interpolator;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LIPB)
  #undef LIPB
#endif
#if defined(_WIN32) && defined(CUBIC)
  #undef CUBIC
#endif
#if defined(_WIN32) && defined(DUBINS)
  #undef DUBINS
#endif
#if defined(_WIN32) && defined(LINEAR)
  #undef LINEAR
#endif


  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> LIPB;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> CUBIC;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> DUBINS;
  static const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> LINEAR;

  typedef boost::shared_ptr< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToRequest_

typedef ::uuv_control_msgs::GoToRequest_<std::allocator<void> > GoToRequest;

typedef boost::shared_ptr< ::uuv_control_msgs::GoToRequest > GoToRequestPtr;
typedef boost::shared_ptr< ::uuv_control_msgs::GoToRequest const> GoToRequestConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToRequest_<ContainerAllocator>::LIPB =
        
          "'lipb'"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToRequest_<ContainerAllocator>::CUBIC =
        
          "'cubic'"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToRequest_<ContainerAllocator>::DUBINS =
        
          "'dubins'"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>
      GoToRequest_<ContainerAllocator>::LINEAR =
        
          "'linear'"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uuv_control_msgs::GoToRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uuv_control_msgs::GoToRequest_<ContainerAllocator1> & lhs, const ::uuv_control_msgs::GoToRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoint == rhs.waypoint &&
    lhs.max_forward_speed == rhs.max_forward_speed &&
    lhs.interpolator == rhs.interpolator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uuv_control_msgs::GoToRequest_<ContainerAllocator1> & lhs, const ::uuv_control_msgs::GoToRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uuv_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca7b4067b6783823c9f5c936e1c99b3a";
  }

  static const char* value(const ::uuv_control_msgs::GoToRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca7b4067b6783823ULL;
  static const uint64_t static_value2 = 0xc9f5c936e1c99b3aULL;
};

template<class ContainerAllocator>
struct DataType< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uuv_control_msgs/GoToRequest";
  }

  static const char* value(const ::uuv_control_msgs::GoToRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"string LIPB='lipb'\n"
"string CUBIC='cubic'\n"
"string DUBINS='dubins'\n"
"string LINEAR='linear'\n"
"\n"
"uuv_control_msgs/Waypoint waypoint\n"
"float64 max_forward_speed\n"
"string interpolator\n"
"\n"
"================================================================================\n"
"MSG: uuv_control_msgs/Waypoint\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"std_msgs/Header header\n"
"geometry_msgs/Point point\n"
"float64 max_forward_speed\n"
"float64 heading_offset\n"
"bool use_fixed_heading\n"
"float64 radius_of_acceptance\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uuv_control_msgs::GoToRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint);
      stream.next(m.max_forward_speed);
      stream.next(m.interpolator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uuv_control_msgs::GoToRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uuv_control_msgs::GoToRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoint: ";
    s << std::endl;
    Printer< ::uuv_control_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoint);
    s << indent << "max_forward_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_forward_speed);
    s << indent << "interpolator: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.interpolator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UUV_CONTROL_MSGS_MESSAGE_GOTOREQUEST_H
