// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accel.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Accel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace uuv_gazebo_plugins_msgs {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* Accel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Accel_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Accel_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Accel_2eproto() {
  protobuf_AddDesc_Accel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Accel.proto");
  GOOGLE_CHECK(file != NULL);
  Accel_descriptor_ = file->message_type(0);
  static const int Accel_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accel, linear_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accel, angular_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accel, time_),
  };
  Accel_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Accel_descriptor_,
      Accel::default_instance_,
      Accel_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accel, _has_bits_[0]),
      -1,
      -1,
      sizeof(Accel),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accel, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Accel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Accel_descriptor_, &Accel::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Accel_2eproto() {
  delete Accel::default_instance_;
  delete Accel_reflection_;
}

void protobuf_AddDesc_Accel_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Accel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gazebo::msgs::protobuf_AddDesc_vector3d_2eproto();
  ::gazebo::msgs::protobuf_AddDesc_time_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Accel.proto\022\034uuv_gazebo_plugins_msgs.m"
    "sgs\032\016vector3d.proto\032\ntime.proto\"w\n\005Accel"
    "\022%\n\006linear\030\001 \002(\0132\025.gazebo.msgs.Vector3d\022"
    "&\n\007angular\030\002 \002(\0132\025.gazebo.msgs.Vector3d\022"
    "\037\n\004time\030\003 \001(\0132\021.gazebo.msgs.Time", 192);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Accel.proto", &protobuf_RegisterTypes);
  Accel::default_instance_ = new Accel();
  Accel::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Accel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Accel_2eproto {
  StaticDescriptorInitializer_Accel_2eproto() {
    protobuf_AddDesc_Accel_2eproto();
  }
} static_descriptor_initializer_Accel_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Accel::kLinearFieldNumber;
const int Accel::kAngularFieldNumber;
const int Accel::kTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Accel::Accel()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:uuv_gazebo_plugins_msgs.msgs.Accel)
}

void Accel::InitAsDefaultInstance() {
  linear_ = const_cast< ::gazebo::msgs::Vector3d*>(&::gazebo::msgs::Vector3d::default_instance());
  angular_ = const_cast< ::gazebo::msgs::Vector3d*>(&::gazebo::msgs::Vector3d::default_instance());
  time_ = const_cast< ::gazebo::msgs::Time*>(&::gazebo::msgs::Time::default_instance());
}

Accel::Accel(const Accel& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:uuv_gazebo_plugins_msgs.msgs.Accel)
}

void Accel::SharedCtor() {
  _cached_size_ = 0;
  linear_ = NULL;
  angular_ = NULL;
  time_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Accel::~Accel() {
  // @@protoc_insertion_point(destructor:uuv_gazebo_plugins_msgs.msgs.Accel)
  SharedDtor();
}

void Accel::SharedDtor() {
  if (this != default_instance_) {
    delete linear_;
    delete angular_;
    delete time_;
  }
}

void Accel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Accel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Accel_descriptor_;
}

const Accel& Accel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Accel_2eproto();
  return *default_instance_;
}

Accel* Accel::default_instance_ = NULL;

Accel* Accel::New(::google::protobuf::Arena* arena) const {
  Accel* n = new Accel;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Accel::Clear() {
// @@protoc_insertion_point(message_clear_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_linear()) {
      if (linear_ != NULL) linear_->::gazebo::msgs::Vector3d::Clear();
    }
    if (has_angular()) {
      if (angular_ != NULL) angular_->::gazebo::msgs::Vector3d::Clear();
    }
    if (has_time()) {
      if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Accel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gazebo.msgs.Vector3d linear = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_linear()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_angular;
        break;
      }

      // required .gazebo.msgs.Vector3d angular = 2;
      case 2: {
        if (tag == 18) {
         parse_angular:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_angular()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_time;
        break;
      }

      // optional .gazebo.msgs.Time time = 3;
      case 3: {
        if (tag == 26) {
         parse_time:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_time()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:uuv_gazebo_plugins_msgs.msgs.Accel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:uuv_gazebo_plugins_msgs.msgs.Accel)
  return false;
#undef DO_
}

void Accel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  // required .gazebo.msgs.Vector3d linear = 1;
  if (has_linear()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->linear_, output);
  }

  // required .gazebo.msgs.Vector3d angular = 2;
  if (has_angular()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->angular_, output);
  }

  // optional .gazebo.msgs.Time time = 3;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->time_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:uuv_gazebo_plugins_msgs.msgs.Accel)
}

::google::protobuf::uint8* Accel::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  // required .gazebo.msgs.Vector3d linear = 1;
  if (has_linear()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->linear_, false, target);
  }

  // required .gazebo.msgs.Vector3d angular = 2;
  if (has_angular()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->angular_, false, target);
  }

  // optional .gazebo.msgs.Time time = 3;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->time_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:uuv_gazebo_plugins_msgs.msgs.Accel)
  return target;
}

int Accel::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  int total_size = 0;

  if (has_linear()) {
    // required .gazebo.msgs.Vector3d linear = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->linear_);
  }

  if (has_angular()) {
    // required .gazebo.msgs.Vector3d angular = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->angular_);
  }

  return total_size;
}
int Accel::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .gazebo.msgs.Vector3d linear = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->linear_);

    // required .gazebo.msgs.Vector3d angular = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->angular_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional .gazebo.msgs.Time time = 3;
  if (has_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->time_);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Accel::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Accel* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Accel>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uuv_gazebo_plugins_msgs.msgs.Accel)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uuv_gazebo_plugins_msgs.msgs.Accel)
    MergeFrom(*source);
  }
}

void Accel::MergeFrom(const Accel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_linear()) {
      mutable_linear()->::gazebo::msgs::Vector3d::MergeFrom(from.linear());
    }
    if (from.has_angular()) {
      mutable_angular()->::gazebo::msgs::Vector3d::MergeFrom(from.angular());
    }
    if (from.has_time()) {
      mutable_time()->::gazebo::msgs::Time::MergeFrom(from.time());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Accel::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Accel::CopyFrom(const Accel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uuv_gazebo_plugins_msgs.msgs.Accel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Accel::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_linear()) {
    if (!this->linear_->IsInitialized()) return false;
  }
  if (has_angular()) {
    if (!this->angular_->IsInitialized()) return false;
  }
  if (has_time()) {
    if (!this->time_->IsInitialized()) return false;
  }
  return true;
}

void Accel::Swap(Accel* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Accel::InternalSwap(Accel* other) {
  std::swap(linear_, other->linear_);
  std::swap(angular_, other->angular_);
  std::swap(time_, other->time_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Accel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Accel_descriptor_;
  metadata.reflection = Accel_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Accel

// required .gazebo.msgs.Vector3d linear = 1;
bool Accel::has_linear() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Accel::set_has_linear() {
  _has_bits_[0] |= 0x00000001u;
}
void Accel::clear_has_linear() {
  _has_bits_[0] &= ~0x00000001u;
}
void Accel::clear_linear() {
  if (linear_ != NULL) linear_->::gazebo::msgs::Vector3d::Clear();
  clear_has_linear();
}
const ::gazebo::msgs::Vector3d& Accel::linear() const {
  // @@protoc_insertion_point(field_get:uuv_gazebo_plugins_msgs.msgs.Accel.linear)
  return linear_ != NULL ? *linear_ : *default_instance_->linear_;
}
::gazebo::msgs::Vector3d* Accel::mutable_linear() {
  set_has_linear();
  if (linear_ == NULL) {
    linear_ = new ::gazebo::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:uuv_gazebo_plugins_msgs.msgs.Accel.linear)
  return linear_;
}
::gazebo::msgs::Vector3d* Accel::release_linear() {
  // @@protoc_insertion_point(field_release:uuv_gazebo_plugins_msgs.msgs.Accel.linear)
  clear_has_linear();
  ::gazebo::msgs::Vector3d* temp = linear_;
  linear_ = NULL;
  return temp;
}
void Accel::set_allocated_linear(::gazebo::msgs::Vector3d* linear) {
  delete linear_;
  linear_ = linear;
  if (linear) {
    set_has_linear();
  } else {
    clear_has_linear();
  }
  // @@protoc_insertion_point(field_set_allocated:uuv_gazebo_plugins_msgs.msgs.Accel.linear)
}

// required .gazebo.msgs.Vector3d angular = 2;
bool Accel::has_angular() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Accel::set_has_angular() {
  _has_bits_[0] |= 0x00000002u;
}
void Accel::clear_has_angular() {
  _has_bits_[0] &= ~0x00000002u;
}
void Accel::clear_angular() {
  if (angular_ != NULL) angular_->::gazebo::msgs::Vector3d::Clear();
  clear_has_angular();
}
const ::gazebo::msgs::Vector3d& Accel::angular() const {
  // @@protoc_insertion_point(field_get:uuv_gazebo_plugins_msgs.msgs.Accel.angular)
  return angular_ != NULL ? *angular_ : *default_instance_->angular_;
}
::gazebo::msgs::Vector3d* Accel::mutable_angular() {
  set_has_angular();
  if (angular_ == NULL) {
    angular_ = new ::gazebo::msgs::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:uuv_gazebo_plugins_msgs.msgs.Accel.angular)
  return angular_;
}
::gazebo::msgs::Vector3d* Accel::release_angular() {
  // @@protoc_insertion_point(field_release:uuv_gazebo_plugins_msgs.msgs.Accel.angular)
  clear_has_angular();
  ::gazebo::msgs::Vector3d* temp = angular_;
  angular_ = NULL;
  return temp;
}
void Accel::set_allocated_angular(::gazebo::msgs::Vector3d* angular) {
  delete angular_;
  angular_ = angular;
  if (angular) {
    set_has_angular();
  } else {
    clear_has_angular();
  }
  // @@protoc_insertion_point(field_set_allocated:uuv_gazebo_plugins_msgs.msgs.Accel.angular)
}

// optional .gazebo.msgs.Time time = 3;
bool Accel::has_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Accel::set_has_time() {
  _has_bits_[0] |= 0x00000004u;
}
void Accel::clear_has_time() {
  _has_bits_[0] &= ~0x00000004u;
}
void Accel::clear_time() {
  if (time_ != NULL) time_->::gazebo::msgs::Time::Clear();
  clear_has_time();
}
const ::gazebo::msgs::Time& Accel::time() const {
  // @@protoc_insertion_point(field_get:uuv_gazebo_plugins_msgs.msgs.Accel.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
::gazebo::msgs::Time* Accel::mutable_time() {
  set_has_time();
  if (time_ == NULL) {
    time_ = new ::gazebo::msgs::Time;
  }
  // @@protoc_insertion_point(field_mutable:uuv_gazebo_plugins_msgs.msgs.Accel.time)
  return time_;
}
::gazebo::msgs::Time* Accel::release_time() {
  // @@protoc_insertion_point(field_release:uuv_gazebo_plugins_msgs.msgs.Accel.time)
  clear_has_time();
  ::gazebo::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
void Accel::set_allocated_time(::gazebo::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:uuv_gazebo_plugins_msgs.msgs.Accel.time)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace uuv_gazebo_plugins_msgs

// @@protoc_insertion_point(global_scope)
