// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Double.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Double.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace uuv_gazebo_plugins_msgs {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* Double_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Double_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Double_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Double_2eproto() {
  protobuf_AddDesc_Double_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Double.proto");
  GOOGLE_CHECK(file != NULL);
  Double_descriptor_ = file->message_type(0);
  static const int Double_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Double, value_),
  };
  Double_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Double_descriptor_,
      Double::default_instance_,
      Double_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Double, _has_bits_[0]),
      -1,
      -1,
      sizeof(Double),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Double, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Double_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Double_descriptor_, &Double::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Double_2eproto() {
  delete Double::default_instance_;
  delete Double_reflection_;
}

void protobuf_AddDesc_Double_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Double_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014Double.proto\022\034uuv_gazebo_plugins_msgs."
    "msgs\"\032\n\006Double\022\020\n\005value\030\001 \002(\001:\0010", 72);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Double.proto", &protobuf_RegisterTypes);
  Double::default_instance_ = new Double();
  Double::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Double_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Double_2eproto {
  StaticDescriptorInitializer_Double_2eproto() {
    protobuf_AddDesc_Double_2eproto();
  }
} static_descriptor_initializer_Double_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Double::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Double::Double()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:uuv_gazebo_plugins_msgs.msgs.Double)
}

void Double::InitAsDefaultInstance() {
}

Double::Double(const Double& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:uuv_gazebo_plugins_msgs.msgs.Double)
}

void Double::SharedCtor() {
  _cached_size_ = 0;
  value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Double::~Double() {
  // @@protoc_insertion_point(destructor:uuv_gazebo_plugins_msgs.msgs.Double)
  SharedDtor();
}

void Double::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Double::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Double::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Double_descriptor_;
}

const Double& Double::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Double_2eproto();
  return *default_instance_;
}

Double* Double::default_instance_ = NULL;

Double* Double::New(::google::protobuf::Arena* arena) const {
  Double* n = new Double;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Double::Clear() {
// @@protoc_insertion_point(message_clear_start:uuv_gazebo_plugins_msgs.msgs.Double)
  value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Double::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:uuv_gazebo_plugins_msgs.msgs.Double)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double value = 1 [default = 0];
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &value_)));
          set_has_value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:uuv_gazebo_plugins_msgs.msgs.Double)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:uuv_gazebo_plugins_msgs.msgs.Double)
  return false;
#undef DO_
}

void Double::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:uuv_gazebo_plugins_msgs.msgs.Double)
  // required double value = 1 [default = 0];
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:uuv_gazebo_plugins_msgs.msgs.Double)
}

::google::protobuf::uint8* Double::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:uuv_gazebo_plugins_msgs.msgs.Double)
  // required double value = 1 [default = 0];
  if (has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:uuv_gazebo_plugins_msgs.msgs.Double)
  return target;
}

int Double::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:uuv_gazebo_plugins_msgs.msgs.Double)
  int total_size = 0;

  // required double value = 1 [default = 0];
  if (has_value()) {
    total_size += 1 + 8;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Double::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uuv_gazebo_plugins_msgs.msgs.Double)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Double* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Double>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uuv_gazebo_plugins_msgs.msgs.Double)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uuv_gazebo_plugins_msgs.msgs.Double)
    MergeFrom(*source);
  }
}

void Double::MergeFrom(const Double& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uuv_gazebo_plugins_msgs.msgs.Double)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Double::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uuv_gazebo_plugins_msgs.msgs.Double)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Double::CopyFrom(const Double& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uuv_gazebo_plugins_msgs.msgs.Double)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Double::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Double::Swap(Double* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Double::InternalSwap(Double* other) {
  std::swap(value_, other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Double::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Double_descriptor_;
  metadata.reflection = Double_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Double

// required double value = 1 [default = 0];
bool Double::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Double::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
void Double::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
void Double::clear_value() {
  value_ = 0;
  clear_has_value();
}
 double Double::value() const {
  // @@protoc_insertion_point(field_get:uuv_gazebo_plugins_msgs.msgs.Double.value)
  return value_;
}
 void Double::set_value(double value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:uuv_gazebo_plugins_msgs.msgs.Double.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace uuv_gazebo_plugins_msgs

// @@protoc_insertion_point(global_scope)
